"""empty message

Revision ID: 18f7e9d71458
Revises: e7372cbcf2bb
Create Date: 2020-07-20 17:20:10.700369

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '18f7e9d71458'
down_revision = 'e7372cbcf2bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user') as batch_op:
        batch_op.add_column(sa.Column('mailing_list', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('unread_announcements', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'unread_announcements')
    op.drop_column('user', 'mailing_list')
    # ### end Alembic commands ###
