"""empty message

Revision ID: 7d2f2933f1b1
Revises: 18f7e9d71458
Create Date: 2020-07-25 17:40:03.331442

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7d2f2933f1b1'
down_revision = '18f7e9d71458'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plan') as batch_op:
        batch_op.drop_column('kw6')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plan', sa.Column('kw6', sa.BOOLEAN(), nullable=False))
    # ### end Alembic commands ###
