"""empty message

Revision ID: b7ff65b769cb
Revises: 7d2f2933f1b1
Create Date: 2020-07-27 11:33:35.393522

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b7ff65b769cb'
down_revision = '7d2f2933f1b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user') as batch_op:
        batch_op.add_column(sa.Column('not_interested', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'not_interested')
    # ### end Alembic commands ###
